# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 026ad5394198e2ecb7427a276b4d67f702aa4393c67fc149b5b60442e191accfc02c904850e63e35230d9b47ae8815e8f3d6345fc99f00769a7ebdd9637d3655

test:
  secret_key_base: 7ca1b9f81150098fa9fe5af48911814122141d451be4abd5c49a09cabeef29787f549c63e8b761b6bee3620d4fb9e723c8d22799e210b52fbde8e3ca7b876df6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
